### ISSUE TITLE
Add "hpc-carpentry" topic to repository

### ISSUE THREAD

**Issue by cgross95** [carpentries-incubator/hpc-workflows#15]
Without the hpc-carpentry topic, this lesson [gets filtered out](https://github.com/hpc-carpentry/hpc-carpentry.github.io/blob/61c79eb61505c326d08afaf0c2726efda28d1322/feeds/hpc-carpentry_lessons.R#L52) when the website data is built, so doesn't show up under [The Carpentries Incubator](https://www.hpc-carpentry.org/community-lessons/#the-carpentries-incubator) section of the lesson page.

**Comment by ocaisa** [comment]
Good catch, I've added it. I'll trigger a website rebuild
